language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - mongodb

env:
  global:
    - NODE_ENV=test

before_script:
  - sleep 15
  - mongo todoAppTest --eval 'db.createUser({user:"bilush",pwd:"test",roles:["readWrite"]});'

script:
  - npm test
after_success:
  - npm run coverage
