language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - mongodb

env:
  global:
    - CC_TEST_REPORTER_ID=c4135e27bedc02ce514005983ae51f418568c8c7005ada07f18b9c955b88565f
    - NODE_ENV=test

before_script:
  - sleep 15
  - mongo todoAppTest --eval 'db.createUser({user:"bilush",pwd:"test",roles:["readWrite"]});'

script:
  - npm test
after_success:
  - npm run coverage
